module.exports = {
    // 框架菜单
    menu: [{
        menuId: 0,
        home: '首页',
        menuName: '主数据中心',
        region: '地址信息管理',
        shipper: '货主管理',
        unit: '单位管理',
        unitMath: '物料单位换算管理',
        materialData: '物料数据管理',
        materialGroup: '物料组管理',
        delivery: '送达方管理',
        sold: '售达方管理',
        business: '事业部管理',
        carriers: '承运商管理',
        driver: '司机管理',
        carManage: '车辆管理',
        factoryDc: '工厂库存地',
        warehouse: '仓库管理',
        shipperWarehouseStrategy: '分仓策略管理',
        unloading: '卸货点管理',
        message: '经销商管理',
        material: '物料信息'
    }, {
        menuId: 1,
        menuName: '系统管理',
        user: '用户管理',
        role: '角色管理',
        resource: '资源管理',
        appRight: '应用权限管理',
        dataRight: '数据权限组管理',
        org: '组织机构管理',
        log: '日志管理'
    }, {
        menuId: 2,
        menuName: '订单中心',
        sourceOrder: '来源订单管理',
        orderManage: '订单管理',
        inStorage: '入库分仓管理',
        outStorage: '出库分仓管理',
        outStoragePlan: '出库计划管理',
        inStoragePlan: '入库计划管理',
        distribution: '配送单管理',
        processOrder: '加工订单管理',
        storage: '库存量管理',
        warning: '预警管理',
        salesOrderList: '销售订单列表',
        buyOrderList: '采购订单列表',
        moveOrderList: '移库订单列表'
    }, {
        menuId: 3,
        menuName: '可视化中心'
    }, {
        menuId: 4,
        menuName: '规则配置中心',
        orderBase: '订单基础节点管理',
        orderNodeClass: '订单节点分类管理',
        orderExtension: '订单节点扩展配置',
        addressMap: '地址映射配置'
    }],
    // 框架顶部右侧
    navTop: {
        search: '请输入要搜索的内容',
        admin: '管理员',
        exit: '退出',
        logo: {
            title: '益海嘉里',
            des: 'OMS平台'
        }
    },
    // 公共按钮
    button: {
        add: '增加',
        remove: '删除',
        update: '修改',
        view: '查看',
        enable: '启用',
        disable: '禁用',
        cancel: '取消',
        confirm: '确定',
        save: '保存',
        close: '关闭',
        search: '查询',
        reset: '重置',
        importExcel: '导入',
        exportExcel: '导出',
        upload: '上传',
        download: '下载',
        resetPassword: '重置密码'
    }
};
